title: The Northern Illinois Association of Teachers of Mathematics
email: your-email@example.com
description: >- # this means to ignore newlines until "baseurl:"
  NIATM (Northern Illinois Association of Teachers of Mathematics)
  Associate Affiliate of the National Council of Teachers of
  Mathematics Serving Winnebago, Boone, and other counties in northern
  Illinois.  The purposes of NIATM is to encourage an active interest
  in all areas of mathematics and mathematics education, to afford a
  medium of interchange of views regarding the teaching of mathematics
  and related disciplines, and to further the study of problems
  relating to the teaching of mathematics and computer science.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: NIATMath
facebook_username: https://www.facebook.com/niatmath
github_username: NIATMath

# Don't hide events in the future
future: true

# Build settings
theme: minima
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag

collections:
  members:
    output: true
  events:
    output: true

defaults:
  - scope:
      path: ""
      type: "members"
    values:
      layout: "member"
  - scope:
      path: "assets/**"
    values:
      sitemap: false

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
